# Документация: https://golangci-lint.run/usage/configuration/
version: "2"


run:
  timeout: 5m
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - errcheck      # Проверяет, что все ошибки обрабатываются.
    - govet         # Стандартный анализатор Go, находит подозрительные конструкции.
    - ineffassign   # Находит неэффективные присваивания (x = x).
    - staticcheck   # Огромный набор статических проверок, очень мощный.

    - bodyclose     # Проверяет, что тела HTTP-ответов закрываются (resp.Body.Close()).
    - contextcheck  # Проверяет, что context.Context передается первым аргументом.
    - dogsled       # Находит избыточные присваивания.
    - dupl          # Находит дублирующийся код.
    - goconst       # Находит строки, которые можно вынести в константы.
    - gocritic      # Огромный набор стилистических и производительных проверок.
    - revive        # Замена golint, проверяет стиль кода.
    - unconvert     # Находит ненужные преобразования типов.
    - unparam       # Находит неиспользуемые параметры функций.
    - wastedassign  # Находит бесполезные присваивания.

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Printf
      - fmt.Sprintf
      - fmt.Errorf

  goimports:
    local-prefixes: avito

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
    - linters:
        - revive
      text: "have comment or be unexported"

    - linters:
        - errcheck
      text: "error returned from Close"
